language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t dev-docker-react-kube -f Dockerfile.dev .

script:
  - docker run -e CI=true dev-docker-react-kube npm run test -- --coverage

deploy:
  provider: "elasticbeanstalk"
  region: "ap-southeast-1"
  app: "dev-docker-react-kube"
  env: "Devdockerreactkube-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-080354175868"
  bucket_path: "dev-docker-react-kube"
  on:
    branch: main
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: 
    secure: "$SECRET_ACCESS_KEY"