language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t dev-docker-react-kube -f Dockerfile.dev .

script:
  - docker run -e CI=true dev-docker-react-kube npm run test

